theme = "catppuccin_mocha" # ferra 

[editor]
line-number = "absolute"
mouse = true
true-color = true
shell = ["fish", "-C"]
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
# Highlight all lines with a cursor
cursorline = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "│"
render = true

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
right = ["primary-selection-length", "total-line-numbers"]

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
